/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWarehouseRouteImport } from './routes/_authenticated/warehouse'
import { Route as AuthenticatedTransactionRouteImport } from './routes/_authenticated/transaction'
import { Route as AuthenticatedSoldProductsRouteImport } from './routes/_authenticated/sold-products'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedIncomeDetailsRouteImport } from './routes/_authenticated/income-details'
import { Route as AuthenticatedExpenseDetailsRouteImport } from './routes/_authenticated/expense-details'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWarehouseRoute = AuthenticatedWarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTransactionRoute =
  AuthenticatedTransactionRouteImport.update({
    id: '/transaction',
    path: '/transaction',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSoldProductsRoute =
  AuthenticatedSoldProductsRouteImport.update({
    id: '/sold-products',
    path: '/sold-products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIncomeDetailsRoute =
  AuthenticatedIncomeDetailsRouteImport.update({
    id: '/income-details',
    path: '/income-details',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExpenseDetailsRoute =
  AuthenticatedExpenseDetailsRouteImport.update({
    id: '/expense-details',
    path: '/expense-details',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expense-details': typeof AuthenticatedExpenseDetailsRoute
  '/income-details': typeof AuthenticatedIncomeDetailsRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sold-products': typeof AuthenticatedSoldProductsRoute
  '/transaction': typeof AuthenticatedTransactionRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/expense-details': typeof AuthenticatedExpenseDetailsRoute
  '/income-details': typeof AuthenticatedIncomeDetailsRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sold-products': typeof AuthenticatedSoldProductsRoute
  '/transaction': typeof AuthenticatedTransactionRoute
  '/warehouse': typeof AuthenticatedWarehouseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/expense-details': typeof AuthenticatedExpenseDetailsRoute
  '/_authenticated/income-details': typeof AuthenticatedIncomeDetailsRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sold-products': typeof AuthenticatedSoldProductsRoute
  '/_authenticated/transaction': typeof AuthenticatedTransactionRoute
  '/_authenticated/warehouse': typeof AuthenticatedWarehouseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/expense-details'
    | '/income-details'
    | '/menu'
    | '/reports'
    | '/settings'
    | '/sold-products'
    | '/transaction'
    | '/warehouse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/expense-details'
    | '/income-details'
    | '/menu'
    | '/reports'
    | '/settings'
    | '/sold-products'
    | '/transaction'
    | '/warehouse'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/expense-details'
    | '/_authenticated/income-details'
    | '/_authenticated/menu'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/sold-products'
    | '/_authenticated/transaction'
    | '/_authenticated/warehouse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/warehouse': {
      id: '/_authenticated/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof AuthenticatedWarehouseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/transaction': {
      id: '/_authenticated/transaction'
      path: '/transaction'
      fullPath: '/transaction'
      preLoaderRoute: typeof AuthenticatedTransactionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sold-products': {
      id: '/_authenticated/sold-products'
      path: '/sold-products'
      fullPath: '/sold-products'
      preLoaderRoute: typeof AuthenticatedSoldProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/income-details': {
      id: '/_authenticated/income-details'
      path: '/income-details'
      fullPath: '/income-details'
      preLoaderRoute: typeof AuthenticatedIncomeDetailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expense-details': {
      id: '/_authenticated/expense-details'
      path: '/expense-details'
      fullPath: '/expense-details'
      preLoaderRoute: typeof AuthenticatedExpenseDetailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExpenseDetailsRoute: typeof AuthenticatedExpenseDetailsRoute
  AuthenticatedIncomeDetailsRoute: typeof AuthenticatedIncomeDetailsRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSoldProductsRoute: typeof AuthenticatedSoldProductsRoute
  AuthenticatedTransactionRoute: typeof AuthenticatedTransactionRoute
  AuthenticatedWarehouseRoute: typeof AuthenticatedWarehouseRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExpenseDetailsRoute: AuthenticatedExpenseDetailsRoute,
  AuthenticatedIncomeDetailsRoute: AuthenticatedIncomeDetailsRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSoldProductsRoute: AuthenticatedSoldProductsRoute,
  AuthenticatedTransactionRoute: AuthenticatedTransactionRoute,
  AuthenticatedWarehouseRoute: AuthenticatedWarehouseRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
